# --- Schema 43: candidate catalogue and preliminary access -----------------

# The catalogue profiles every parser identity. It deliberately does not infer
# canonical equivalence or economic semantics: source labels and governed
# metadata remain visible, and mechanical eligibility is a separate status from
# research admission.
create_catalog_explore_views <- function(con) {
  DBI::dbExecute(con, "CREATE SCHEMA IF NOT EXISTS catalog")
  DBI::dbExecute(con, "CREATE SCHEMA IF NOT EXISTS explore")

  # Carry observation lineage from the declared staging natural key. The unique
  # index rejects ambiguous keys at write time; the profile also compares raw
  # matches with distinct observation keys so a damaged constraint still
  # quarantines the whole candidate before any locator can be exposed.
  observation_lineage_sql <- paste(
    "SELECT vintage_id,series_id,period,1::BIGINT AS lineage_match_count,",
    " source_sheet,table_title,parser_mode,source_row,source_column,source_period_label,",
    " category,measure,question,response,entity_id,exchange_item_id,participant_id",
    " FROM staging.documented_series_snapshot",
    " WHERE parser_mode <> 'lrm_auction_event_governed_consolidation'",
    " UNION ALL SELECT d.vintage_id,d.series_id,d.period,l.lineage_match_count,",
    " d.source_sheet,d.table_title,d.parser_mode,NULL::BIGINT,NULL::BIGINT,d.source_period_label,",
    " d.category,d.measure,d.question,d.response,d.entity_id,d.exchange_item_id,d.participant_id",
    " FROM staging.documented_series_snapshot d",
    " JOIN (SELECT vintage_id,derived_series_id,period,count(*)::BIGINT AS lineage_match_count",
    "  FROM staging.lrm_derived_observation_lineage GROUP BY 1,2,3) l ON l.vintage_id=d.vintage_id",
    " AND l.derived_series_id=d.series_id AND l.period=d.period",
    " WHERE d.parser_mode='lrm_auction_event_governed_consolidation'"
  )

  profile_sql <- paste(
    "WITH observation_lineage AS (", observation_lineage_sql, "), observed AS (",
    " SELECT o.*,d.frequency,lag(o.period_start) OVER(",
    "  PARTITION BY o.series_id ORDER BY o.period_start,o.period) AS previous_period_start",
    " FROM main.v_series_latest o JOIN canonical.dim_series d USING(series_id)",
    "), observation_metrics AS (",
    " SELECT series_id,count(*) AS observation_count,count(value) AS non_missing_observation_count,",
    " min(period_start) AS earliest_period,max(period_end) AS latest_period,",
    " any_value(vintage_id) AS current_vintage_id,any_value(source_file) AS current_source_file,",
    " count(*) FILTER(WHERE period_start IS NULL OR period_end IS NULL OR period_end<period_start)",
    "  AS malformed_period_count,",
    " count(*) FILTER(WHERE value IS NULL) AS null_value_count,",
    " count(*) FILTER(WHERE value IS NOT NULL AND NOT isfinite(value)) AS nonfinite_value_count,",
    " count(*) FILTER(WHERE previous_period_start IS NOT NULL AND (",
    "  (frequency='annual' AND date_diff('month',previous_period_start,period_start)>12) OR",
    "  (frequency='semiannual' AND date_diff('month',previous_period_start,period_start)>6) OR",
    "  (frequency='quarterly' AND date_diff('month',previous_period_start,period_start)>3) OR",
    "  (frequency IN ('monthly','monthly_survey') AND",
    "   date_diff('month',previous_period_start,period_start)>1))) AS gap_count,",
    " coalesce(sum(CASE WHEN previous_period_start IS NULL THEN 0",
    "  WHEN frequency='annual' THEN greatest(floor(date_diff('month',previous_period_start,period_start)/12.0)-1,0)",
    "  WHEN frequency='semiannual' THEN greatest(floor(date_diff('month',previous_period_start,period_start)/6.0)-1,0)",
    "  WHEN frequency='quarterly' THEN greatest(floor(date_diff('month',previous_period_start,period_start)/3.0)-1,0)",
    "  WHEN frequency IN ('monthly','monthly_survey') THEN",
    "   greatest(date_diff('month',previous_period_start,period_start)-1,0) ELSE 0 END),0)::BIGINT",
    "  AS estimated_skipped_periods",
    " FROM observed GROUP BY series_id",
    "), bounded_overlap_signatures AS (",
    # A bounded, evidence-backed overlap population. The census identified the
    # thirty Cuadro 20 / dedicated FX date-value pairs; recomputing their small
    # signatures keeps the classification reproducible without burdening every
    # catalogue query with a 1.2-million-row all-pairs screen.
    " SELECT o.series_id,d.source_id,count(*) AS n,md5(string_agg(",
    "  strftime(o.period_start,'%Y-%m-%d')||':'||printf('%.17g',o.value),",
    "  '|' ORDER BY o.period_start,o.period)) AS observation_signature",
    " FROM observed o JOIN canonical.dim_series d USING(series_id)",
    " WHERE d.source_id='fx_operations' OR",
    "  (d.source_id='economic_annex' AND d.series_id LIKE 'economic_annex:cuadro_20:%')",
    " GROUP BY o.series_id,d.source_id",
    "), supported_overlaps AS (",
    " SELECT a.series_id,count(DISTINCT b.series_id) AS supported_overlap_series_count,",
    " string_agg(DISTINCT b.series_id,';' ORDER BY b.series_id) AS supported_overlap_series_ids",
    " FROM bounded_overlap_signatures a JOIN bounded_overlap_signatures b",
    " ON a.observation_signature=b.observation_signature AND a.n=b.n",
    "  AND a.source_id<>b.source_id GROUP BY a.series_id",
    "), normalized_keys AS (",
    " SELECT series_id,count(*) FILTER(WHERE n>1) AS duplicate_logical_key_count,",
    " count(*) FILTER(WHERE n>1 AND distinct_values>1) AS conflicting_logical_key_count",
    " FROM (SELECT series_id,period_start,count(*) AS n,count(DISTINCT value) AS distinct_values",
    "  FROM observed GROUP BY series_id,period_start) x GROUP BY series_id",
    "), expected AS (",
    " SELECT series_id,count(*) AS expected_period_count",
    " FROM staging.expected_observation_grid GROUP BY series_id",
    "), missing AS (",
    " SELECT series_id,count(*) AS expected_missing_count,",
    " string_agg(DISTINCT reason,';' ORDER BY reason) AS expected_missing_reasons",
    " FROM staging.observation_missingness GROUP BY series_id",
    "), titles AS (",
    " SELECT series_id,any_value(source_sheet) AS title_record_source_sheet,",
    " any_value(table_title) AS title_record_table_title,",
    " bool_or(title_varies_by_vintage) AS title_varies_by_vintage",
    " FROM main.v_series_titles GROUP BY series_id",
    "), dimensions AS (",
    " SELECT series_id,any_value(product) AS product,any_value(trade_flow) AS trade_flow,",
    " any_value(trade_classification) AS trade_classification,any_value(trade_regime) AS trade_regime,",
    " any_value(measure) AS parsed_measure",
    " FROM main.v_series_dimensions GROUP BY series_id",
    "), domains AS (",
    " SELECT series_id,any_value(domain) AS domain,any_value(subdomain) AS subdomain,",
    " any_value(measure_family) AS measure_family,any_value(domain_reviewed_by) AS domain_reviewed_by",
    " FROM main.v_series_domain GROUP BY series_id",
    "), table_states AS (",
    " SELECT series_id,string_agg(DISTINCT status,';' ORDER BY status) AS table_status,",
    " bool_or(lower(coalesce(status,'')) IN",
    "  ('needs_remodeling','quarantine','quarantined','invalid','excluded'))",
    "  AS table_is_invalid,any_value(status_note) AS table_status_note",
    " FROM main.v_series_table_status GROUP BY series_id",
    "), lineage AS (",
    " SELECT o.series_id,",
    " count(s.series_id) AS source_observation_lineage_rows,",
    " count(s.series_id) FILTER(WHERE s.source_sheet IS NOT NULL",
    "  AND ((s.source_row IS NOT NULL AND s.source_column IS NOT NULL)",
    "   OR s.parser_mode='lrm_auction_event_governed_consolidation')) AS coordinate_lineage_rows,",
    " count(s.series_id) FILTER(WHERE s.series_id IS NOT NULL",
    "  AND (s.source_sheet IS NULL OR ((s.source_row IS NULL OR s.source_column IS NULL)",
    "  AND s.parser_mode<>'lrm_auction_event_governed_consolidation'))) AS invalid_lineage_rows,",
    " count(s.series_id) FILTER(WHERE s.series_id IS NOT NULL AND (",
    "  t.title_record_source_sheet IS DISTINCT FROM s.source_sheet OR",
    "  t.title_record_table_title IS DISTINCT FROM s.table_title)) AS worksheet_lineage_correction_rows,",
    " count(DISTINCT s.source_sheet) FILTER(WHERE s.source_sheet IS NOT NULL) AS source_sheet_count,",
    " string_agg(DISTINCT s.source_sheet,';' ORDER BY s.source_sheet) FILTER(",
    "  WHERE s.source_sheet IS NOT NULL) AS source_sheets,",
    " count(DISTINCT s.table_title) FILTER(WHERE s.table_title IS NOT NULL) AS table_title_count,",
    " string_agg(DISTINCT s.table_title,';' ORDER BY s.table_title) FILTER(",
    "  WHERE s.table_title IS NOT NULL) AS table_titles,",
    " any_value(s.parser_mode) AS parser_method,min(s.source_row) AS example_source_row,",
    " min(s.source_column) AS example_source_column,",
    " string_agg(DISTINCT s.category,';' ORDER BY s.category) FILTER(WHERE s.category IS NOT NULL)",
    "  AS source_categories,",
    " string_agg(DISTINCT s.measure,';' ORDER BY s.measure) FILTER(WHERE s.measure IS NOT NULL)",
    "  AS source_measures,",
    " string_agg(DISTINCT s.question,';' ORDER BY s.question) FILTER(WHERE s.question IS NOT NULL)",
    "  AS source_questions,",
    " string_agg(DISTINCT s.response,';' ORDER BY s.response) FILTER(WHERE s.response IS NOT NULL)",
    "  AS source_responses,",
    " string_agg(DISTINCT s.entity_id,';' ORDER BY s.entity_id) FILTER(WHERE s.entity_id IS NOT NULL)",
    "  AS source_entity_ids,",
    " string_agg(DISTINCT s.exchange_item_id,';' ORDER BY s.exchange_item_id)",
    "  FILTER(WHERE s.exchange_item_id IS NOT NULL) AS source_exchange_item_ids,",
    " string_agg(DISTINCT s.participant_id,';' ORDER BY s.participant_id)",
    "  FILTER(WHERE s.participant_id IS NOT NULL) AS source_participant_ids",
    " FROM main.v_series_latest o LEFT JOIN observation_lineage s",
    " ON s.series_id=o.series_id AND s.period=o.period AND s.vintage_id=o.vintage_id",
    " LEFT JOIN titles t ON t.series_id=o.series_id",
    " GROUP BY o.series_id",
    "), source_metadata AS (",
    " SELECT source_id,any_value(source_label) AS source_dataset,any_value(publisher) AS source_institution,",
    " any_value(source_format) AS source_format FROM raw.source_files GROUP BY source_id",
    "), active_flags AS (",
    " SELECT d.series_id,",
    " count(q.check_id) FILTER(WHERE q.severity='error') AS applicable_error_count,",
    " count(q.check_id) FILTER(WHERE q.severity='warning') AS applicable_quality_warning_count,",
    " string_agg(DISTINCT q.check_name,';' ORDER BY q.check_name) AS applicable_quality_checks",
    " FROM canonical.dim_series d LEFT JOIN titles t USING(series_id)",
    " LEFT JOIN research.quality_flags q ON q.series_id=d.series_id OR (q.series_id IS NULL",
    "  AND q.source_id=d.source_id AND (q.source_sheet IS NULL",
    "   OR q.source_sheet=t.title_record_source_sheet))",
    " GROUP BY d.series_id",
    "), admitted AS (",
    " SELECT series_id,any_value(research_series_id) AS research_series_id,",
    " any_value(assurance_level) AS research_assurance_level,",
    " any_value(certification_rule_id) AS research_certification_rule_id",
    " FROM main.v_certified_research_series GROUP BY series_id",
    "), assembled AS (",
    " SELECT d.series_id AS candidate_id,",
    " coalesce(nullif(d.canonical_name,''),d.source_label,d.label) AS researcher_name,",
    " CASE WHEN nullif(d.canonical_name,'') IS NOT NULL THEN 'reviewed_canonical_name'",
    "  ELSE 'source_label' END AS researcher_name_basis,",
    " d.source_label AS original_source_label,d.full_series_path,d.source_id,sm.source_dataset,",
    " sm.source_institution,sm.source_format,",
    " CASE WHEN coalesce(li.source_sheet_count,0)=1",
    "  AND coalesce(li.coordinate_lineage_rows,0)=coalesce(om.observation_count,0)",
    "  THEN li.source_sheets END AS source_sheet,",
    " CASE WHEN coalesce(li.table_title_count,0)=1 THEN li.table_titles END AS table_title,",
    " li.source_sheet_count,li.source_sheets,li.table_title_count,li.table_titles,",
    " t.title_record_source_sheet,t.title_record_table_title,t.title_varies_by_vintage,",
    " dm.domain,dm.subdomain,dm.measure_family,dm.domain_reviewed_by,",
    " dx.product,dx.trade_flow,dx.trade_classification,dx.trade_regime,dx.parsed_measure,",
    " d.series_grain AS data_structure,d.identity_basis,d.identity_stability,d.semantic_status,",
    " d.frequency,CASE WHEN d.frequency IS NULL THEN 'unknown'",
    "  ELSE 'parser_assigned_requires_verification' END AS frequency_basis,",
    " om.earliest_period,om.latest_period,coalesce(om.observation_count,0) AS observation_count,",
    " coalesce(om.non_missing_observation_count,0) AS non_missing_observation_count,",
    " CASE WHEN coalesce(om.observation_count,0)<3 THEN 'too_short_to_assess'",
    "  WHEN d.frequency IN ('irregular_daily','irregular_interval','daily') THEN 'irregular_by_contract'",
    "  WHEN coalesce(om.malformed_period_count,0)>0 THEN 'malformed'",
    "  WHEN coalesce(om.gap_count,0)>0 THEN 'gaps_detected' ELSE 'regular_observed' END AS date_regularity,",
    " coalesce(om.gap_count,0) AS gap_count,coalesce(om.estimated_skipped_periods,0) AS estimated_skipped_periods,",
    " coalesce(e.expected_period_count,0) AS expected_grid_period_count,",
    " coalesce(m.expected_missing_count,0) AS expected_missing_count,m.expected_missing_reasons,",
    " CASE WHEN e.series_id IS NULL THEN 'no_expected_grid_constructed'",
    "  ELSE 'expected_grid_available' END AS expected_grid_status,",
    " coalesce(nk.duplicate_logical_key_count,0) AS duplicate_logical_key_count,",
    " coalesce(nk.conflicting_logical_key_count,0) AS conflicting_logical_key_count,",
    " coalesce(om.malformed_period_count,0) AS malformed_period_count,",
    " coalesce(om.null_value_count,0) AS null_value_count,",
    " coalesce(om.nonfinite_value_count,0) AS nonfinite_value_count,",
    " coalesce(xo.supported_overlap_series_count,0) AS supported_overlap_series_count,",
    " xo.supported_overlap_series_ids,",
    " d.unit AS source_unit,d.unit_code,d.scale AS source_scale,d.scale_multiplier,d.currency,",
    " d.index_base,d.price_base_year,d.measure_type,d.stock_flow,d.nominal_real,",
    " d.seasonal_adjustment,d.transformation,d.valuation,d.hierarchy_level,d.parent_series_id,",
    " d.is_total,d.hierarchy_status,coalesce(ts.table_status,'not_recorded') AS table_status,",
    " ts.table_status_note,coalesce(af.applicable_error_count,0) AS applicable_error_count,",
    " coalesce(af.applicable_quality_warning_count,0) AS applicable_quality_warning_count,",
    " af.applicable_quality_checks,om.current_vintage_id,om.current_source_file,p.sha256 AS source_sha256,",
    " p.publication_date,p.official_release_date,p.official_url,p.release_identifier,p.available_at,",
    " p.availability_quality,p.license,p.provenance_status,li.parser_method,",
    " 'not_recorded_use_build_code_digest' AS parser_version_status,",
    " (SELECT max(version) FROM audit.schema_version) AS database_schema_version,",
    " (SELECT schema_version FROM audit.build_identity ORDER BY built_at DESC LIMIT 1) AS build_schema_version,",
    " (SELECT code_digest FROM audit.build_identity ORDER BY built_at DESC LIMIT 1) AS build_code_digest,",
    " split_part(d.identity_basis,'|',1) AS identity_source_sheet,",
    " coalesce(li.source_observation_lineage_rows,0) AS source_observation_lineage_rows,",
    " coalesce(li.coordinate_lineage_rows,0) AS coordinate_lineage_rows,",
    " greatest(coalesce(om.observation_count,0)-",
    "  coalesce(li.source_observation_lineage_rows,0),0) AS missing_lineage_rows,",
    " coalesce(li.invalid_lineage_rows,0) AS invalid_lineage_rows,",
    " greatest(coalesce(li.source_observation_lineage_rows,0)-",
    "  coalesce(om.observation_count,0),0) AS ambiguous_lineage_rows,",
    " coalesce(li.worksheet_lineage_correction_rows,0) AS worksheet_lineage_correction_rows,",
    " li.example_source_row,",
    " li.example_source_column,li.source_categories,li.source_measures,li.source_questions,",
    " li.source_responses,li.source_entity_ids,li.source_exchange_item_ids,li.source_participant_ids,",
    " CASE WHEN coalesce(li.coordinate_lineage_rows,0)=coalesce(om.observation_count,0)",
    "  AND coalesce(om.observation_count,0)>0 THEN 'complete_for_current_observations'",
    "  WHEN coalesce(li.coordinate_lineage_rows,0)>0 THEN 'partial_for_current_observations'",
    "  ELSE 'fact_and_vintage_lineage_only' END AS coordinate_lineage_status,",
    " CASE WHEN greatest(coalesce(li.source_observation_lineage_rows,0)-",
    "  coalesce(om.observation_count,0),0)>0 THEN 'ambiguous_source_observation'",
    "  WHEN coalesce(li.invalid_lineage_rows,0)>0 THEN 'invalid_source_observation_locator'",
    "  WHEN coalesce(li.coordinate_lineage_rows,0)=coalesce(om.observation_count,0)",
    "   AND coalesce(om.observation_count,0)>0 AND coalesce(li.source_sheet_count,0)>1",
    "   THEN 'complete_multiple_worksheets'",
    "  WHEN coalesce(li.coordinate_lineage_rows,0)=coalesce(om.observation_count,0)",
    "   AND coalesce(om.observation_count,0)>0 THEN 'complete_single_worksheet'",
    "  WHEN coalesce(li.coordinate_lineage_rows,0)>0 THEN 'partial_source_observation_lineage'",
    "  ELSE 'fact_and_vintage_lineage_only' END AS worksheet_lineage_status,",
    " CASE WHEN coalesce(li.worksheet_lineage_correction_rows,0)=0 THEN NULL",
    "  WHEN coalesce(li.source_sheet_count,0)>1 THEN",
    "   'series_title_record_represents_one_of_multiple_worksheets;observation_lineage_uses_exact_documented_snapshot'",
    "  WHEN t.title_record_source_sheet IS NULL THEN",
    "   'series_title_record_missing_worksheet;observation_lineage_uses_exact_documented_snapshot'",
    "  ELSE 'series_title_record_differs_from_observation_lineage;observation_lineage_uses_exact_documented_snapshot'",
    "  END AS worksheet_lineage_correction_reason,",
    " a.research_series_id,a.research_assurance_level,a.research_certification_rule_id,",
    " coalesce(ts.table_is_invalid,FALSE) AS table_is_invalid",
    " FROM canonical.dim_series d LEFT JOIN observation_metrics om ON om.series_id=d.series_id",
    " LEFT JOIN supported_overlaps xo ON xo.series_id=d.series_id",
    " LEFT JOIN normalized_keys nk ON nk.series_id=d.series_id LEFT JOIN expected e ON e.series_id=d.series_id",
    " LEFT JOIN missing m ON m.series_id=d.series_id LEFT JOIN titles t ON t.series_id=d.series_id",
    " LEFT JOIN dimensions dx ON dx.series_id=d.series_id LEFT JOIN domains dm ON dm.series_id=d.series_id",
    " LEFT JOIN table_states ts ON ts.series_id=d.series_id LEFT JOIN lineage li ON li.series_id=d.series_id",
    " LEFT JOIN source_metadata sm ON sm.source_id=d.source_id LEFT JOIN active_flags af ON af.series_id=d.series_id",
    " LEFT JOIN admitted a ON a.series_id=d.series_id LEFT JOIN main.v_source_provenance p",
    "  ON p.vintage_id=om.current_vintage_id",
    "), tiered AS (",
    " SELECT *,CASE",
    "  WHEN table_is_invalid OR applicable_error_count>0 OR malformed_period_count>0",
    "   OR null_value_count>0 OR nonfinite_value_count>0 OR duplicate_logical_key_count>0",
    "   OR conflicting_logical_key_count>0 OR invalid_lineage_rows>0",
    "   OR ambiguous_lineage_rows>0 THEN 'quarantined_or_invalid'",
    "  WHEN research_assurance_level IS NOT NULL THEN 'research_ready'",
    "  WHEN data_structure<>'scalar_series' OR frequency='irregular_interval'",
    "   THEN 'non_scalar_or_special_structure'",
    "  WHEN identity_stability<>'semantic' THEN 'candidate_needs_review'",
    "  WHEN non_missing_observation_count>0",
    "   THEN 'exploratory_structurally_valid'",
    "  WHEN non_missing_observation_count<3 THEN 'candidate_needs_review'",
    "  ELSE 'exploratory_structurally_valid' END AS validation_tier",
    " FROM assembled",
    "), classified AS (",
    " SELECT *,CASE",
    "  WHEN source_id='lrm_auctions' AND identity_stability IN ('positional','positional_lane')",
    "   THEN 'source_event_identity_unresolved'",
    "  WHEN source_id='cda_curve' AND identity_stability IN ('positional','positional_lane')",
    "   THEN 'source_curve_identity_unresolved'",
    "  WHEN source_id='lrm_auctions' AND (unit_code IS NULL OR unit_code='UNRESOLVED_SOURCE_UNITS')",
    "   THEN 'source_rate_unit_unresolved'",
    "  WHEN source_id='cda_curve' AND (unit_code IS NULL OR unit_code='UNRESOLVED_SOURCE_UNITS')",
    "   THEN 'source_rate_or_volume_unit_unresolved'",
    "  WHEN validation_tier='quarantined_or_invalid' THEN 'mechanical_integrity_failed'",
    "  WHEN validation_tier='research_ready' THEN 'admitted_to_research'",
    "  WHEN validation_tier='non_scalar_or_special_structure' THEN 'dedicated_structure_required'",
    "  WHEN validation_tier='candidate_needs_review' THEN CASE WHEN identity_stability<>'semantic'",
    "   THEN 'identity_requires_review' ELSE 'insufficient_scalar_history' END",
    "  ELSE 'mechanically_eligible_semantic_review_incomplete' END AS status_code,",
    " CASE",
    "  WHEN source_id='lrm_auctions' AND identity_stability='semantic_event'",
    "   AND unit_code IS NOT NULL AND unit_code<>'UNRESOLVED_SOURCE_UNITS' THEN 'explore.events'",
    "  WHEN source_id='lrm_auctions' THEN NULL",
    "  WHEN source_id='cda_curve' AND identity_stability IN ('positional','positional_lane')",
    "   THEN NULL",
    "  WHEN validation_tier='research_ready' THEN 'research.observations_latest_actual'",
    "  WHEN validation_tier='exploratory_structurally_valid' THEN 'explore.observations'",
    "  WHEN validation_tier='non_scalar_or_special_structure'",
    "   AND (data_structure='event' OR frequency='irregular_interval') THEN 'explore.events'",
    "  WHEN validation_tier='non_scalar_or_special_structure' AND data_structure='entity_panel'",
    "   THEN 'explore.panel_observations'",
    "  WHEN validation_tier='non_scalar_or_special_structure' AND data_structure='curve_panel'",
    "   THEN 'explore.curve_observations' ELSE NULL END AS observation_interface,",
    " CASE",
    "  WHEN source_id='lrm_auctions' AND identity_stability IN ('positional','positional_lane') THEN 'LRM event retained with exact lineage but withheld because the workbook supplies no field that separates colliding auction-tenor rows.'",
    "  WHEN source_id='cda_curve' AND identity_stability IN ('positional','positional_lane') THEN 'CDA curve node retained with exact lineage but withheld because the worksheet omits the institution heading.'",
    "  WHEN source_id='lrm_auctions' AND (unit_code IS NULL OR unit_code='UNRESOLVED_SOURCE_UNITS') THEN 'LRM offered/assigned rate meaning is explicit, but its unit is not stated in the workbook; retained in catalog and withheld from explore.*.'",
    "  WHEN source_id='lrm_auctions' THEN 'Corrected LRM amount or bid-count event measure with stable tenor identity and exact source-cell lineage; provisional exploration only.'",
    "  WHEN source_id='cda_curve' AND (unit_code IS NULL OR unit_code='UNRESOLVED_SOURCE_UNITS') THEN 'CDA curve node is retained with exact lineage, but the workbook does not establish a usable rate or value unit/scale; catalog-only pending evidence.'",
    "  WHEN validation_tier='research_ready' THEN 'Admitted to research.* at the stated assurance level; inspect remaining provenance and source warnings.'",
    "  WHEN validation_tier='exploratory_structurally_valid' THEN 'Mechanical retrieval checks pass; economic meaning, completeness, continuity and comparability require verification.'",
    "  WHEN validation_tier='candidate_needs_review' THEN 'Discoverable candidate; ordinary exploratory retrieval is withheld pending identity or short-series review.'",
    "  WHEN validation_tier='quarantined_or_invalid' THEN 'Known mechanical or governed-status defect; observations are not exposed through explore.*.'",
    "  ELSE 'Special data structure; use the stated grain-specific interface and preserve its native dimensions.' END",
    "  AS concise_warning",
    " FROM tiered",
    "), admission AS (",
    " SELECT *,CASE",
    "  WHEN validation_tier='quarantined_or_invalid' THEN 'clear_mechanical_defect'",
    "  WHEN validation_tier='research_ready' AND research_assurance_level='human_verified'",
    "   THEN 'research_admitted_human_verified'",
    "  WHEN validation_tier='research_ready' THEN 'research_admitted_rule_certified'",
    "  WHEN supported_overlap_series_count>0 THEN 'probable_duplicate_or_overlap'",
    "  WHEN source_id='lrm_auctions' AND identity_stability IN ('positional','positional_lane') THEN 'probable_identity_fragmentation'",
    "  WHEN source_id='lrm_auctions' AND (unit_code IS NULL OR unit_code='UNRESOLVED_SOURCE_UNITS') THEN 'insufficient_evidence'",
    "  WHEN source_id='cda_curve' AND (unit_code IS NULL OR unit_code='UNRESOLVED_SOURCE_UNITS') THEN 'insufficient_evidence'",
    "  WHEN source_id='lrm_auctions' THEN 'apparently_valid_preliminary'",
    "  WHEN validation_tier='candidate_needs_review'",
    "   AND identity_stability IN ('positional','positional_lane')",
    "   THEN 'probable_identity_fragmentation'",
    "  WHEN validation_tier='candidate_needs_review' THEN 'insufficient_evidence'",
    "  WHEN observation_count=0 THEN 'discovery_only'",
    "  ELSE 'apparently_valid_preliminary' END AS primary_review_category,",
    " 'deterministic_profile_rule' AS classification_basis,",
    " 'post_promotion_series_quality_v1' AS classification_rule_id,",
    " '1.1.0' AS classification_rule_version,",
    " 'discoverable' AS catalog_admission_status,",
    " CASE",
    "  WHEN source_id='lrm_auctions' AND identity_stability='semantic_event'",
    "   AND unit_code IS NOT NULL AND unit_code<>'UNRESOLVED_SOURCE_UNITS' THEN 'eligible_native_grain'",
    "  WHEN source_id='lrm_auctions' THEN 'withheld'",
    "  WHEN source_id='cda_curve' AND identity_stability IN ('positional','positional_lane')",
    "   THEN 'withheld'",
    "  WHEN source_id='cda_curve' AND (unit_code IS NULL OR unit_code='UNRESOLVED_SOURCE_UNITS') THEN 'withheld'",
    "  WHEN validation_tier IN ('research_ready','exploratory_structurally_valid')",
    "   THEN 'eligible_scalar'",
    "  WHEN validation_tier='non_scalar_or_special_structure' THEN 'eligible_native_grain'",
    "  WHEN validation_tier='quarantined_or_invalid' THEN 'quarantined'",
    "  ELSE 'withheld' END AS explore_admission_status,",
    " CASE",
    "  WHEN source_id='lrm_auctions' AND identity_stability IN ('positional','positional_lane')",
    "   THEN 'published_event_key_not_unique'",
    "  WHEN source_id='cda_curve' AND identity_stability IN ('positional','positional_lane')",
    "   THEN 'published_institution_heading_missing'",
    "  WHEN source_id='lrm_auctions' AND (unit_code IS NULL OR unit_code='UNRESOLVED_SOURCE_UNITS')",
    "   THEN 'source_rate_unit_unresolved'",
    "  WHEN source_id='cda_curve' AND (unit_code IS NULL OR unit_code='UNRESOLVED_SOURCE_UNITS')",
    "   THEN 'source_rate_or_volume_unit_unresolved'",
    "  WHEN validation_tier IN ('research_ready','exploratory_structurally_valid',",
    "   'non_scalar_or_special_structure') THEN NULL",
    "  WHEN validation_tier='quarantined_or_invalid' THEN 'mechanical_integrity_failed'",
    "  WHEN identity_stability IN ('positional','positional_lane')",
    "   THEN 'preliminary_identity_not_stable'",
    "  ELSE 'insufficient_scalar_history' END AS explore_exclusion_reason,",
    " CASE WHEN validation_tier='research_ready' THEN 'admitted'",
    "  ELSE 'not_admitted' END AS research_admission_status,",
    " CASE",
    "  WHEN validation_tier='research_ready' THEN NULL",
    "  WHEN validation_tier='quarantined_or_invalid' THEN 'mechanical_integrity_failed'",
    "  WHEN identity_stability IN ('positional','positional_lane')",
    "   THEN 'stable_economic_identity_not_established'",
    "  WHEN data_structure<>'scalar_series' OR frequency='irregular_interval'",
    "   THEN 'native_grain_research_certification_incomplete'",
    "  WHEN non_missing_observation_count<3 THEN 'insufficient_history_for_review'",
    "  ELSE 'formal_series_review_incomplete' END AS research_exclusion_reason,",
    " CASE",
    "  WHEN research_assurance_level='human_verified' THEN 'human_verified'",
    "  WHEN research_assurance_level='rule_certified' THEN 'rule_certified_not_human_verified'",
    "  ELSE 'economic_semantics_not_formally_verified' END AS semantic_review_status,",
    " CASE WHEN provenance_status='complete' AND availability_quality='publisher_verified'",
    "  THEN 'complete_publisher_verified' ELSE 'incomplete_or_not_publisher_verified' END",
    "  AS provenance_review_status,",
    " CASE",
    "  WHEN validation_tier='quarantined_or_invalid' THEN 'failed'",
    "  WHEN coordinate_lineage_status='complete_for_current_observations'",
    "   THEN 'reconciled_with_coordinates'",
    "  ELSE 'reconciled_with_coordinate_limitations' END AS parser_reconciliation_status,",
    " CASE WHEN observation_count>0 AND non_missing_observation_count>0",
    "  THEN 'current_numeric_observations_available' ELSE 'no_current_numeric_observations' END",
    "  AS current_observation_availability,",
    " concat_ws(';',",
    "  CASE WHEN validation_tier='quarantined_or_invalid' THEN 'mechanical_integrity_failed' END,",
    "  CASE WHEN identity_stability IN ('positional','positional_lane')",
    "   THEN 'positional_identity_fragmentation_risk' END,",
    "  CASE WHEN supported_overlap_series_count>0 THEN 'verified_cross_source_value_overlap' END,",
    "  CASE WHEN source_id='lrm_auctions' AND identity_stability IN ('positional','positional_lane')",
    "   THEN 'lrm_published_event_key_collision' END,",
    "  CASE WHEN data_structure='scalar_series' AND non_missing_observation_count<3",
    "   THEN 'short_scalar_history' END,",
    "  CASE WHEN data_structure<>'scalar_series' OR frequency='irregular_interval'",
    "   THEN 'native_grain_required' END,",
    "  CASE WHEN unit_code IS NULL OR unit_code='UNRESOLVED_SOURCE_UNITS'",
    "   THEN 'unit_semantics_unresolved' END,",
    "  CASE WHEN gap_count>0 THEN 'periodicity_gap_review_indicator' END,",
    "  CASE WHEN coordinate_lineage_status<>'complete_for_current_observations'",
    "   THEN 'coordinate_lineage_limited' END,",
    "  CASE WHEN provenance_status IS NULL OR provenance_status<>'complete'",
    "   OR availability_quality IS NULL OR availability_quality<>'publisher_verified'",
    "   THEN 'provenance_review_incomplete' END,",
    "  CASE WHEN research_assurance_level IS NULL THEN 'formal_research_review_incomplete' END)",
    "  AS classification_issue_codes",
    " FROM classified",
    "), warned AS (",
    " SELECT *,concat_ws(';',",
    "  CASE validation_tier",
    "   WHEN 'research_ready' THEN 'research_admission_with_stated_assurance'",
    "   WHEN 'exploratory_structurally_valid' THEN 'economic_semantic_review_incomplete'",
    "   WHEN 'candidate_needs_review' THEN 'candidate_not_exposed_as_ordinary_series'",
    "   WHEN 'quarantined_or_invalid' THEN 'mechanical_or_governed_invalidity'",
    "   ELSE 'dedicated_structure_required' END,",
    "  'frequency_parser_assigned_requires_verification',",
    "  CASE WHEN unit_code IS NULL OR unit_code='UNRESOLVED_SOURCE_UNITS' THEN 'unit_requires_verification' END,",
    "  CASE WHEN stock_flow IS NULL OR stock_flow='not_reviewed' THEN 'stock_flow_requires_verification' END,",
    "  CASE WHEN seasonal_adjustment IS NULL OR seasonal_adjustment='not_reviewed'",
    "   THEN 'seasonal_adjustment_requires_verification' END,",
    "  CASE WHEN transformation IS NULL OR transformation='not_reviewed' THEN 'transformation_requires_verification' END,",
    "  CASE WHEN hierarchy_status IS NULL OR hierarchy_status='unresolved' THEN 'hierarchy_requires_verification' END,",
    "  CASE WHEN identity_stability IN ('positional','positional_lane')",
    "   THEN 'positional_identity_requires_review' END,",
    "  CASE WHEN supported_overlap_series_count>0",
    "   THEN 'verified_cross_source_value_overlap' END,",
    "  CASE WHEN source_id='lrm_auctions' AND identity_stability IN ('positional','positional_lane')",
    "   THEN 'lrm_published_event_key_collision' END,",
    "  CASE WHEN data_structure='scalar_series' AND non_missing_observation_count<3 THEN 'short_scalar_candidate' END,",
    "  CASE WHEN gap_count>0 THEN 'declared_frequency_gaps_detected' END,",
    "  CASE WHEN expected_grid_status='no_expected_grid_constructed' THEN 'no_expected_grid_constructed' END,",
    "  CASE WHEN provenance_status IS NULL OR provenance_status<>'complete' THEN 'source_provenance_incomplete' END,",
    "  CASE WHEN availability_quality IS NULL OR availability_quality<>'publisher_verified'",
    "   THEN 'availability_not_publisher_verified' END,",
    "  CASE WHEN coordinate_lineage_status<>'complete_for_current_observations'",
    "   THEN 'coordinate_lineage_incomplete' END,",
    "  CASE WHEN table_status<>'validated' THEN 'table_not_economically_validated' END,",
    "  CASE WHEN applicable_quality_warning_count>0 THEN 'active_quality_flags_present' END)",
    "  AS warning_codes",
    " FROM admission",
    ") SELECT * EXCLUDE(table_is_invalid),",
    " array_length(string_split(warning_codes,';')) AS warning_count,",
    " CASE WHEN validation_tier='research_ready' THEN 'formal'",
    "  WHEN validation_tier='exploratory_structurally_valid' THEN 'preliminary_with_warnings'",
    "  WHEN validation_tier='non_scalar_or_special_structure' THEN 'specialized_structure'",
    "  ELSE 'blocked' END AS usability_level,",
    " 'catalog.profile(candidate_id)' AS profile_interface",
    " FROM warned"
  )
  create_project_view(con, "series", profile_sql, schema = "catalog")

  readiness_sql <- paste(
    "WITH family AS (SELECT source_id AS family,any_value(source_institution) AS source,",
    " count(*) AS series_total,count(*) FILTER(WHERE explore_admission_status LIKE 'eligible%')",
    "  AS series_already_accessible,",
    " count(*) FILTER(WHERE explore_admission_status='withheld' AND observation_count>0",
    "  AND validation_tier='candidate_needs_review')",
    "  AS additional_releasable_series,",
    " coalesce(sum(observation_count) FILTER(WHERE explore_admission_status='withheld'",
    "  AND observation_count>0 AND validation_tier='candidate_needs_review'),0)",
    "  AS additional_observations,",
    " count(*) FILTER(WHERE unit_code IS NULL OR unit_code='UNRESOLVED_SOURCE_UNITS') AS unresolved_units,",
    " count(*) FILTER(WHERE frequency IS NULL OR malformed_period_count>0) AS ambiguous_time,",
    " count(*) FILTER(WHERE identity_stability IN ('positional','positional_lane')) AS positional_ids,",
    " sum(conflicting_logical_key_count) AS collisions,",
    " count(*) FILTER(WHERE supported_overlap_series_count>0) AS overlap_series,",
    " count(*) FILTER(WHERE transformation IS NULL OR transformation='not_reviewed') AS unknown_transformations,",
    " count(*) FILTER(WHERE semantic_status IS NULL OR semantic_status<>'reviewed') AS methodology_uncertainty,",
    " count(*) FILTER(WHERE hierarchy_status IS NULL OR hierarchy_status='unresolved') AS complex_hierarchy,",
    " count(*) FILTER(WHERE data_structure<>'scalar_series') AS specialized_series,",
    " count(*) FILTER(WHERE parser_reconciliation_status<>'reconciled_with_coordinates') AS incomplete_reconciliation,",
    " count(*) FILTER(WHERE applicable_error_count>0) AS parser_errors,",
    " count(*) FILTER(WHERE parser_method IS NOT NULL AND identity_stability='semantic') AS structured_metadata,",
    " count(*) FILTER(WHERE identity_stability='semantic') AS semantic_ids,",
    " count(*) FILTER(WHERE parser_reconciliation_status='reconciled_with_coordinates') AS reconciled_series,",
    " count(*) FILTER(WHERE source_categories IS NOT NULL OR source_entity_ids IS NOT NULL",
    "  OR source_participant_ids IS NOT NULL) AS explicit_dimensions",
    " FROM catalog.series GROUP BY source_id), scored AS (SELECT *,",
    "  1.5::DOUBLE AS fixed_hours_assumption,0.03::DOUBLE AS variable_hours_per_series_assumption,",
    "  0.06::DOUBLE AS unresolved_unit_penalty_hours,0.12::DOUBLE AS ambiguous_time_penalty_hours,",
    "  0.08::DOUBLE AS positional_identity_penalty_hours,0.50::DOUBLE AS collision_penalty_hours,",
    "  0.04::DOUBLE AS overlap_penalty_hours,0.04::DOUBLE AS unknown_transformation_penalty_hours,",
    "  0.05::DOUBLE AS methodology_penalty_hours,0.03::DOUBLE AS hierarchy_penalty_hours,",
    "  0.05::DOUBLE AS specialized_structure_penalty_hours,0.08::DOUBLE AS reconciliation_penalty_hours,",
    "  1.00::DOUBLE AS parser_error_penalty_hours FROM family), scored_cost AS (SELECT *,",
    " variable_hours_per_series_assumption*additional_releasable_series +",
    " unresolved_unit_penalty_hours*unresolved_units + ambiguous_time_penalty_hours*ambiguous_time +",
    " positional_identity_penalty_hours*positional_ids + collision_penalty_hours*collisions +",
    " overlap_penalty_hours*overlap_series + unknown_transformation_penalty_hours*unknown_transformations +",
    " methodology_penalty_hours*methodology_uncertainty + hierarchy_penalty_hours*complex_hierarchy +",
    " specialized_structure_penalty_hours*specialized_series +",
    " reconciliation_penalty_hours*incomplete_reconciliation + parser_error_penalty_hours*parser_errors",
    " AS estimated_variable_hours FROM scored), costed AS (SELECT *,",
    " fixed_hours_assumption + estimated_variable_hours AS estimated_total_hours FROM scored_cost)",
    " SELECT *,fixed_hours_assumption AS estimated_fixed_hours,",
    " additional_releasable_series/nullif(estimated_total_hours,0) AS releasable_series_per_hour,",
    " CASE WHEN parser_errors>0 OR collisions>0 THEN 'low'",
    "  WHEN ambiguous_time>0 OR incomplete_reconciliation>0 THEN 'medium' ELSE 'high' END",
    "  AS estimate_confidence,",
    " concat_ws(';',CASE WHEN unresolved_units>0 THEN 'unresolved_units' END,",
    "  CASE WHEN ambiguous_time>0 THEN 'ambiguous_frequency_or_period' END,",
    "  CASE WHEN positional_ids>0 THEN 'positional_identities' END,",
    "  CASE WHEN collisions>0 THEN 'collisions' END,CASE WHEN overlap_series>0 THEN 'overlaps' END,",
    "  CASE WHEN parser_errors>0 THEN 'active_parser_errors' END) AS predominant_blocks,",
    " CASE WHEN parser_errors>0 OR collisions>0 THEN 'repair_before_exposure'",
    "  WHEN positional_ids>0 AND additional_releasable_series>0 THEN 'stabilize_series_identity'",
    "  WHEN additional_releasable_series>0 THEN 'review_preliminary_admission'",
    "  WHEN specialized_series>0 THEN 'use_native_grain_interface' ELSE 'no_incremental_action' END",
    "  AS recommended_action,",
    " CASE WHEN specialized_series>0 AND additional_releasable_series=0 THEN 'explore.native_grain'",
    "  ELSE 'explore.observations' END AS target_interface",
    " FROM costed ORDER BY releasable_series_per_hour DESC NULLS LAST,family"
  )
  create_project_view(con, "family_readiness", readiness_sql, schema = "catalog")

  create_project_view(con, "series_warnings", paste(
    "SELECT s.candidate_id,s.source_id,s.source_institution,s.current_source_file,",
    " s.current_vintage_id,s.source_sha256,s.validation_tier,s.status_code,s.concise_warning,",
    " u.warning_code,CASE u.warning_code",
    " WHEN 'economic_semantic_review_incomplete' THEN 'Economic and semantic review is incomplete.'",
    " WHEN 'candidate_not_exposed_as_ordinary_series' THEN 'The candidate is discoverable but not eligible for ordinary scalar retrieval.'",
    " WHEN 'mechanical_or_governed_invalidity' THEN 'A mechanical integrity check or governed table status prevents exposure.'",
    " WHEN 'dedicated_structure_required' THEN 'Use the grain-specific interface and retain native dimensions.'",
    " WHEN 'short_scalar_candidate' THEN 'Fewer than three current non-missing observations are available.'",
    " WHEN 'positional_identity_requires_review' THEN 'The identifier depends on a workbook position or lane and may move in a future publication.'",
    " WHEN 'declared_frequency_gaps_detected' THEN 'Observed normalized periods skip one or more declared regular steps.'",
    " WHEN 'coordinate_lineage_incomplete' THEN 'Fact and vintage lineage exists, but source coordinates are unavailable for some current rows.'",
    " WHEN 'verified_cross_source_value_overlap' THEN 'An exact varying date-value population is also published under the comparison-group candidate identifiers.'",
    " WHEN 'lrm_published_event_key_collision' THEN 'The workbook supplies no auction identifier that separates these same-date and same-tenor LRM rows; they remain catalog-only.'",
    " WHEN 'source_provenance_incomplete' THEN 'Official source provenance fields are incomplete.'",
    " WHEN 'availability_not_publisher_verified' THEN 'Availability is not supported by a publisher-verified release timestamp.'",
    " ELSE replace(u.warning_code,'_',' ') END AS warning",
    " FROM catalog.series s CROSS JOIN unnest(string_split(s.warning_codes,';')) u(warning_code)"
  ), schema = "catalog")

  create_project_view(con, "datasets", paste(
    "WITH series_counts AS (SELECT source_id,count(*) AS candidate_series,",
    " sum(observation_count)::BIGINT AS current_series_observations,",
    " count(*) FILTER(WHERE validation_tier='research_ready') AS research_ready_series,",
    " count(*) FILTER(WHERE validation_tier='exploratory_structurally_valid') AS exploratory_series,",
    " count(*) FILTER(WHERE validation_tier='candidate_needs_review') AS review_series,",
    " count(*) FILTER(WHERE validation_tier='quarantined_or_invalid') AS invalid_series,",
    " count(*) FILTER(WHERE validation_tier='non_scalar_or_special_structure') AS special_series,",
    " min(earliest_period) AS earliest_period,max(latest_period) AS latest_period,",
    " string_agg(DISTINCT source_sheets,';' ORDER BY source_sheets) FILTER(WHERE source_sheets IS NOT NULL) AS source_sheets,",
    " string_agg(DISTINCT table_titles,';' ORDER BY table_titles) FILTER(WHERE table_titles IS NOT NULL) AS table_titles",
    " FROM catalog.series GROUP BY source_id), source_files AS (",
    " SELECT f.source_id,any_value(f.source_file) AS source_file,any_value(f.sha256) AS source_sha256,",
    " any_value(f.vintage_id) AS current_vintage_id FROM raw.source_files f",
    " JOIN audit.release_sources r USING(vintage_id)",
    " JOIN audit.active_data_release a ON a.source_bundle_id=r.release_id GROUP BY f.source_id",
    ") SELECT d.*,coalesce(s.candidate_series,0) AS candidate_series,",
    " coalesce(s.current_series_observations,0) AS current_series_observations,",
    " coalesce(s.research_ready_series,0) AS research_ready_series,",
    " coalesce(s.exploratory_series,0) AS exploratory_series,coalesce(s.review_series,0) AS review_series,",
    " coalesce(s.invalid_series,0) AS invalid_series,coalesce(s.special_series,0) AS special_series,",
    " s.earliest_period,s.latest_period,s.source_sheets,s.table_titles,f.source_file,f.source_sha256,",
    " f.current_vintage_id,p.provenance_status,p.availability_quality,",
    " CASE WHEN d.source_id='corporate_bond_curves' THEN 'research.curves'",
    "  WHEN d.source_id='securities_trades' THEN 'research.transactions'",
    "  WHEN d.source_id IN ('banks','financial') THEN 'research.entity_panel'",
    "  WHEN coalesce(s.exploratory_series,0)>0 THEN 'explore.observations'",
    "  WHEN coalesce(s.special_series,0)>0 THEN 'catalog.series' ELSE 'catalog.datasets' END",
    "  AS access_interface,",
    " CASE WHEN d.grain IN ('event','entity_panel','curve_panel') OR d.source_id IN",
    "  ('corporate_bond_curves','securities_trades','banks','financial')",
    "  THEN 'non_scalar_or_special_structure' ELSE 'candidate_needs_review' END AS validation_tier,",
    " 'dataset_status_requires_series_or_native_grain_review' AS status_code,",
    " 'Dataset status is not series-level economic validation; inspect catalogue warnings and the native access grain.'",
    "  AS concise_warning,",
    " 'dataset_grain_status;source_provenance_and_license_limits_apply' AS warning_codes,",
    " 2::BIGINT AS warning_count",
    " FROM canonical.dataset_catalog d LEFT JOIN series_counts s USING(source_id)",
    " LEFT JOIN source_files f USING(source_id) LEFT JOIN main.v_source_provenance p",
    "  ON p.vintage_id=f.current_vintage_id"
  ), schema = "catalog")

  DBI::dbExecute(con, paste0(
    "CREATE OR REPLACE MACRO catalog.profile(requested_id) AS TABLE (",
    "SELECT * FROM catalog.series s WHERE s.candidate_id=requested_id)"
  ))

  observation_select <- paste(
    "WITH observation_lineage AS (", observation_lineage_sql, ")",
    "SELECT o.series_id AS candidate_id,s.researcher_name,s.original_source_label,",
    " s.full_series_path,s.data_structure,s.identity_basis,s.identity_stability,",
    " s.identity_source_sheet,o.period AS source_period_date,",
    " o.period_start AS reference_period_start,o.period_end AS reference_period_end,o.value,",
    " s.frequency,s.frequency_basis,s.source_unit,s.unit_code,s.source_scale,s.scale_multiplier,",
    " s.currency,s.stock_flow,s.nominal_real,s.seasonal_adjustment,s.transformation,s.valuation,",
    " s.product,s.trade_flow,s.trade_classification,s.trade_regime,s.parsed_measure,",
    " s.source_categories,s.source_measures,s.source_questions,s.source_responses,",
    " s.source_entity_ids,s.source_exchange_item_ids,s.source_participant_ids,",
    " o.observation_status,o.vintage_id,o.publication_date,p.available_at,p.availability_quality,",
    " s.source_id,s.source_institution,o.source_file,d.source_sheet,d.table_title,",
    " s.title_record_source_sheet,s.title_record_table_title,",
    " d.parser_mode AS parser_method,d.source_row,d.source_column,d.source_period_label,",
    " s.database_schema_version,s.build_schema_version,s.build_code_digest,s.coordinate_lineage_status,",
    " CASE WHEN d.parser_mode='lrm_auction_event_governed_consolidation'",
    "  AND d.lineage_match_count>0 THEN 'governed_derived_multi_cell'",
    "  WHEN d.lineage_match_count>1 THEN 'ambiguous_source_observation'",
    "  WHEN d.lineage_match_count=1 AND (d.source_sheet IS NULL OR d.source_row IS NULL",
    "   OR d.source_column IS NULL) THEN 'invalid_source_observation_locator'",
    "  WHEN d.lineage_match_count=1 THEN 'source_observation_exact'",
    "  ELSE 'fact_and_vintage_lineage_only' END AS worksheet_lineage_status,",
    " CASE WHEN d.lineage_match_count<>1 OR d.lineage_match_count IS NULL THEN NULL",
    "  WHEN s.title_record_source_sheet IS DISTINCT FROM d.source_sheet",
    "   AND s.title_record_source_sheet IS NULL THEN",
    "   'series_title_record_missing_worksheet;observation_lineage_uses_exact_documented_snapshot'",
    "  WHEN s.title_record_source_sheet IS DISTINCT FROM d.source_sheet THEN",
    "   'series_title_record_worksheet_differs;observation_lineage_uses_exact_documented_snapshot'",
    "  WHEN s.title_record_table_title IS DISTINCT FROM d.table_title THEN",
    "   'series_title_record_title_differs;observation_lineage_uses_exact_documented_snapshot'",
    "  ELSE NULL END AS worksheet_lineage_correction_reason,",
    " s.primary_review_category,s.classification_basis,s.classification_rule_id,",
    " s.classification_rule_version,s.catalog_admission_status,s.explore_admission_status,",
    " s.supported_overlap_series_count,s.supported_overlap_series_ids,",
    " s.explore_exclusion_reason,s.research_admission_status,s.research_exclusion_reason,",
    " s.semantic_review_status,s.provenance_review_status,s.parser_reconciliation_status,",
    " s.current_observation_availability,s.classification_issue_codes,",
    " s.validation_tier,s.status_code,s.concise_warning,s.warning_codes,s.warning_count",
    " FROM main.v_series_latest o JOIN catalog.series s ON s.candidate_id=o.series_id",
    " LEFT JOIN observation_lineage d ON d.series_id=o.series_id",
    "  AND d.period=o.period AND d.vintage_id=o.vintage_id",
    " LEFT JOIN main.v_source_provenance p ON p.vintage_id=o.vintage_id"
  )
  create_project_view(con, "observations", paste(
    observation_select,
    "WHERE s.data_structure='scalar_series' AND s.validation_tier IN",
    " ('research_ready','exploratory_structurally_valid')",
    " AND s.explore_admission_status='eligible_scalar'"
  ), schema = "explore")
  create_project_view(con, "events", paste(
    observation_select,
    "WHERE (s.data_structure='event' OR s.frequency='irregular_interval')",
    " AND s.validation_tier='non_scalar_or_special_structure'",
    " AND s.explore_admission_status='eligible_native_grain'"
  ), schema = "explore")
  create_project_view(con, "panel_observations", paste(
    observation_select,
    "WHERE s.data_structure='entity_panel' AND s.validation_tier='non_scalar_or_special_structure'",
    " AND s.explore_admission_status='eligible_native_grain'"
  ), schema = "explore")
  create_project_view(con, "curve_observations", paste(
    observation_select,
    "WHERE s.data_structure='curve_panel' AND s.validation_tier='non_scalar_or_special_structure'",
    " AND s.explore_admission_status='eligible_native_grain'"
  ), schema = "explore")
  create_project_view(con, "series_catalog", paste(
    "SELECT * FROM catalog.series WHERE observation_interface IN",
    " ('research.observations_latest_actual','explore.observations','explore.events',",
    "  'explore.panel_observations','explore.curve_observations')"
  ), schema = "explore")
  DBI::dbExecute(con, paste0(
    "CREATE OR REPLACE MACRO explore.series(requested_id) AS TABLE (",
    "SELECT * FROM explore.observations o WHERE o.candidate_id=requested_id)"
  ))
  invisible(TRUE)
}
