root <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)
db_path <- file.path(root, "database", "paraguay_macro_pilot.duckdb")
if (!file.exists(db_path)) stop("No version-1 database found; run source('run_update.R') directly.", call. = FALSE)
backup_dir <- file.path(root, "database", "backups")
dir.create(backup_dir, recursive = TRUE, showWarnings = FALSE)
backup <- file.path(backup_dir, paste0("paraguay_macro_pilot_v1_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".duckdb"))
if (!file.copy(db_path, backup)) stop("Could not create the mandatory version-1 backup.", call. = FALSE)
message("Backup created: ", backup)
retired <- paste0(db_path, ".v1_retired")
if (file.exists(retired)) stop("A retired v1 database already exists: ", retired, call. = FALSE)
if (!file.rename(db_path, retired)) stop("Could not retire the version-1 database; close all open database connections and retry.", call. = FALSE)
message("Version-1 database retained as: ", retired)
source(file.path(root, "run_update.R"))
